label sc_004_within_forest:
    scene text forest
    nvl_narrator "Así, la joven y el SER se internaron en el BOSque Marchito"
    nvl_narrator "Caminaron entre los oscuros árboles de desnudas ramas y suelo cubierto de vegetación seca"
    nvl_narrator "Estaba bastante oscuro, pero la luz que emitia HADA les permitía ver lo suficiente como para poder seguir avanzando"
    nvl_narrator "El lugar era intranquilamente silencioso, lóbrego a pesar de ser pleno día"
    nvl_narrator "Pero GIRL avanzaba convencida intentando que su entusiasmo no venciera a su preocupación"
    nvl clear
    nvl_narrator "Entonces, al poco de llevar caminando, el SER y la joven observaron algo muy curioso"
    nvl_narrator "Los primeros brotes de hierba verde, las primeras solitarias hojas en alguna rama de un árbol"
    nvl_narrator "Poco a poco. Muy poco a poco, comenzaban a ver algún signo de vida, aunque muy leve aún"
    nvl_narrator "La joven estaba entusiasmada con el hallazgo, la convenćía para seguir adelante y aumentaba su entusiasmo"
    nvl_narrator "Quizá demasiado"
    scene bg forest dark
    girl "¿Has visto eso? ¡Verde!"
    girl "Ahí hay unos brotes en el suelo, y ahí un pequeño arbusto"
    girl "¡Y ahí hay más!"
    fairy "Sí, lo veo."
    fairy "¿No te resulta... Curioso?"
    "{i}La niña paró un momento y se quedó pensando. Miró a su alrededor, dio un par de pasos y volvió a mirar a HADA{\i}"
    girl "¿Cómo es posible que aquí en el interior, que hay todabía menos luz, haya más plantas que afuera?"
    fairy "Eso mismo me estaba preguntando yo."
    girl "Bueno, seguro que si seguimos avanzando, terminaremos descubriendolo."
    "..."
    "{i}GIRL siguió avanzando con paso firme, pero entonces, sólo unos instantes después, HADA se colocó rápidamente delante de ella"
    fairy "¡Detente! Creo que he visto algo."
    fairy "No, no. No digas nada. Ségueme."
    "{i}Ella miró a HADA con los ojos muy abiertos y asintió con la cabeza siguiendola hasta acercarse hasta el tronco de un grueso árbol que había cerca{\i}"
    fairy "Mira aĺlí. Con cuidado. Hay algo."
    girl "¿Crees que nos ha visto?"
    fairy "No, creo que no. Parece que camina de un lado a otro."
    girl "¿Y ahora que hacemos?"
    fairy "Yo me elevaré un poco y buscaré un lugar seguro sobre el que pasar."
    fairy "Después tendrás que venir hacia mí."
    fairy "Cuando vengas hacia mi, sé precavida. Da un pasa cada vez, y espera a ver que hace la criatura."
    fairy "Entonces da otro paso y vuelve a esperar."
    fairy "Los árboles pueden ayudarte a llegar."
    fairy "Intenta no acercarte demasiado a la criatura."
    girl "Va... Vale."
    girl "Ir pasito a pasito y no acercarme mucho a la criatura. ¡Hecho!"
    jump minigame_1
