label sc_003_before_forest:
    "Los SER son criaturas de fantasía de vibrantes y luminosos colores, salidos de la más pura imaginación"
    "Se dice que estas criaturas se componen de la imaginación , los pensamientos y los sentimientos de otras criaturas que quedan suspendidos en el aire allá por donde pasán"
    "Por eso, dicen, se sienten atraidas por personas imaginativas, sabias y aventureras a las que no dudan en acompañar y ayudar en lo que puedan"
    "También se dice que a parte de los cientos de recuerdos, pensamientos e historias de las que se compoenen guardan la esencia de los ancestros"
    "Es decir, de todos aquellos que ya no están pero que dejaron una huella imborrable"
    "Es por eso que muchos adivinan entre las lenguas llameantes de la magia que les rodea, un corazón. Simbolo de la vida que late dentro de ellas"
    "Sean ciertas o no estás creencias sigue siendo verdad que un SER siempre tratará de traer algo de luz a la oscuridad de la manera que le sea posible"

    scene bg forest
    nene "Pues... Aquí es"
    girl "No sé si este bosque será todas las palabras que dijo el Gran Sabio, pero..."
    girl "No parece un sitio muy animado."
    girl "Eso tiene un punto muy positivo y es que si no hay nadie, nadie puede hacerte daño."
    fairy "Espera, espera."
    girl "¿Eh? ¿Qué?"
    girl "¡Pero si no había nadie!"
    girl "Si antes lo digo..."
    show fairy
    fairy "Tranquila, soy yo."
    girl "Oh, HADA, eres tú."
    girl "Había venido a ver como era el bosque de cerca, después de la historia que nos ha contado el Gran Sabio."
    fairy "Tengo la corazonada de que ibas a algo más que a mirar desde la linde del bosque."
    girl "Vaya, eres muy lista..."
    fairy "Despueś de la historia que nos han contado, ¿Crees que lo más prudente es entrar ahí dentro?"
    girl "Bueno... Pero no parece que haya nada peligroso."
    girl "Está bastante oscuro, pero parece más un sitio aburrido que agresivo."
    fairy "Eso puede ser al principio, pero no sabemos que habrá más allá."
    play sound frozen
    girl "Pues... Pues..."
    girl "Más allá..."
    girl "Podría..."
    fairy "Podría haber algo interesante ¿no?"
    girl "¡Claro! El objeto de la gran maga."
    girl "El que se quedo en el bosque cuando ella..."
    girl "Bueno... Cuando ella..."
    fairy "Desaparecio."
    girl "¡Sí, eso! Cuando ella desapareció."
    girl "El objeto se quedó allí, en el bosque, según la historia del Gran Sabio..."
    fairy "Ni siquiera sabemos si esa historia es verdad."
    girl "Pero, si no lo fuera, eso significaría que el final de la historia es el que ha contado el Gran Sabio."
    girl "¡Y eso no puede ser!"
    girl "El objeto tiene que estar ahí dentro"
    girl "..."
    girl "Sólo hay que..."
    fairy "Está bien, está bien."
    fairy "Te acompañaré."
    fairy "Pero, si el lugar es tan peligroso como cuenta la historia, tendremos que retroceder para no sufir el mismo destino que la gran maga."
    girl "Sí, sí. Está bien."
    girl "¡Gracias HADA!"
    jump sc_004_within_forest