# Display
MASTER_VOLUMEN = 0.1
WIDTH  = 1920
HEIGHT = 1080
#WIDTH  = 1280
#HEIGHT = 720
ASPECT_RELATION_PLAYER = 2.4
ASPECT_RELATION_CHAT = 0.6
WIDTH_PLAYER_SPRITE = 100
HEIGHT_CHAT = 680
WIDTH_OBJECT = 100
WIDTH_OBJECT_ICON = 20

PLAYER_SURFACE = (WIDTH_PLAYER_SPRITE, int(WIDTH_PLAYER_SPRITE * ASPECT_RELATION_PLAYER))
CHAT_SURFACE = (int(HEIGHT_CHAT * ASPECT_RELATION_CHAT), HEIGHT_CHAT)
OBJECT_SURFACE = (WIDTH_OBJECT, WIDTH_OBJECT)
OBJECT_SURFACE_ICON = (WIDTH_OBJECT_ICON, WIDTH_OBJECT_ICON)


# Locations buttons
LOCATION_BUTTON_EMAIL = (WIDTH / 3, HEIGHT / 3)
LOCATION_BUTTON_REVIEW = (WIDTH / 3 * 2, HEIGHT / 3)
LOCATION_BUTTON_BOOKING = (WIDTH / 3, HEIGHT / 3 * 2)
LOCATION_BUTTON_UPGRADES = (WIDTH / 3 * 2, HEIGHT / 3 * 2)

LOCATION_BUTTON_CHANGE_EMAIL_1 = (150, 200)
LOCATION_BUTTON_CHANGE_EMAIL_2 = (150, 400)

LOCATION_BUTTON_ACCEPT_BOOKING = (WIDTH / 2 - 50, 650)
LOCATION_BUTTON_DECLINE_BOOKING = (WIDTH / 2 + 50, 650)

LOCATION_CALENDAR = (1300, 200)

DISPLACEMENT_NAME_BUTTON_CHANGE_EMAIL = (50, 0)
DISPLACEMENT_EMAIL_TEXT_SUBJECT = (0, 200)
DISPLACEMENT_EMAIL_TEXT_SENDER = (0, 400)
DISPLACEMENT_EMAIL_TEXT_BODY = (0, 600)

DISPLACEMENT_CALENDAR_MARKER_0 = (0, 600)
DISPLACEMENT_CALENDAR_MARKER_1 = (0, 600)
DISPLACEMENT_CALENDAR_MARKER_2 = (0, 600)
DISPLACEMENT_CALENDAR_MARKER_3 = (0, 600)



# Level config

# HUB
